- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
      skip: true



# python executable used to run get-pip, create virtualenvs
- name: Define amr_python_executable from internal vars if not explicitly defined
  ansible.builtin.set_fact:
    amr_python_executable: "{{ __amr_python_executable }}"
  when: amr_python_executable is not defined
