


- name: Create group archivematica
  ansible.builtin.group:
    name: archivematica
    gid: 333
    system: true

- name: Create user archivematica
  ansible.builtin.user:
    name: archivematica
    uid: 333
    system: true
    group: archivematica
    home: /var/lib/archivematica

- name: Create directory to hold archivematica source code repositories
  ansible.builtin.file:
    state: directory
    path: "{{ amr_src_path_base }}"
    mode: '0755'

# - Use get-pip.py with --user option to install pip to the 
#   user archivematica install directory ( var/lib/archivematica/.local/ )
# - Do not install globally to avoid conflicts with OS package installs 
#   of pip 
# Ref.
# - https://github.com/pypa/get-pip#usage
# - https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-user
# - https://stackoverflow.com/questions/40852267/installing-pip-locally-without-root-privileges


- name: "Download get-pip.py in archivematica userdir"
  become: true
  become_user: archivematica
  ansible.builtin.get_url:
    url: "https://bootstrap.pypa.io/get-pip.py"
    dest: "/var/lib/archivematica/"

- name: "Install pip with get-pip.py for user archivematica"
  become: true
  become_user: archivematica
  ansible.builtin.command: "{{ amr_python_executable }} get-pip.py --user pip=={{ amr_pip_version }}"
  args:
    chdir: "/var/lib/archivematica"
    creates: /var/lib/archivematica/.local/bin/pip

- name: "Install virtualenv with pip for user archivematica"
  become: true
  become_user: archivematica
  pip:
    name: "virtualenv"
    executable: "{{ amr_pip_executable }}"
    extra_args: "--user"

- name: "Create base directory for virtualenvs will be created"
  file:
    path: "{{ amr_virtualenv_path_base }}"
    owner: "archivematica"
    group: "archivematica"
    state: "directory"

- name: "Create directory in /etc/ for archivematica misc config files"
  file:
    path: "/etc/archivematica"
    owner: "archivematica"
    group: "archivematica"
    state: "directory"
