---
# handlers file for ansible-am

- name: Restart Storage Service (systemd)
  ansible.builtin.systemd_service:
    name: archivematica-storage-service
    state: restarted
    daemon_reload: true

- name: Restart Dashboard (systemd)
  ansible.builtin.systemd_service:
    name: archivematica-dashboard
    state: restarted
    daemon_reload: true
