---
# handlers file for ansible-am

- name: Restart Storage Service (systemd)
  ansible.builtin.systemd_service:
    name: archivematica-storage-service
    state: restarted
    daemon_reload: true

- name: Restart MCP Server (systemd)
  ansible.builtin.systemd_service:
    name: archivematica-mcp-server
    state: restarted
    daemon_reload: true
  listen: Restart Archivematica pipeline (systemd)

- name: Restart MCP Client (systemd)
  ansible.builtin.systemd_service:
    name: archivematica-mcp-client
    state: restarted
    daemon_reload: true
  listen: Restart Archivematica pipeline (systemd)

- name: Restart Dashboard (systemd)
  ansible.builtin.systemd_service:
    name: archivematica-dashboard
    state: restarted
    daemon_reload: true
  listen: Restart Archivematica pipeline (systemd)
  