# - Files in this directory (vars/) contains common variables that should
#   normally be left unchanged (internal use variables)
# - For variables that normally are to be overriden by host_vars or playbooks
#   please use defaults/main.yml instead 
# - Variable names starting with __ are transient variables whose values are
#   assigned to others in tasks/common-vars.yml
#   (they shouldn't be used elsewhere)

# pip executable (used in ansible pip module)
amr_pip_executable: "/var/lib/archivematica/.local/bin/pip"
# virtualenv executable (for virtualenv_command used in ansible pip module)
amr_virtualenv_executable: "/var/lib/archivematica/.local/bin/virtualenv"

# virtualenv paths
amr_virtualenv_path_base: "/usr/share/archivematica/virtualenvs"


# environment vars for django

__amr_ss_environment:
  DJANGO_SETTINGS_MODULE: "storage_service.settings.production"
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_SECRET_KEY: '{{ amr_django_secret_key_ss }}'
  EMAIL_HOST: "localhost"
  EMAIL_HOST_PASSWORD: ""
  EMAIL_HOST_USER: ""
  EMAIL_PORT: "25"
  LANG: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"
  LC_LANG: "en_US.UTF-8"
  REQUESTS_CA_BUNDLE: "{{ amr_requests_ca_bundle }}"
  SS_DB_URL: 'mysql://{{ amr_ss_db_user }}:{{ amr_ss_db_password }}@{{ amr_ss_db_host }}:{{ amr_ss_db_port }}/{{ amr_ss_db_name }}'
  SS_GUNICORN_BIND: "{{ amr_ss_gunicorn_bind }}"
  SS_GUNICORN_CHDIR: "{{ [amr_src_path_base, 'archivematica-storage-service', 'storage_service'] | ansible.builtin.path_join }}"
  SS_GUNICORN_WORKERS: "3"
